# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ gragghia/ci_testing ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  icl_slate:
    timeout-minutes: 120
    strategy:
      matrix:
        maker: [make]
        device: [cpu,gpu_nvidia]
      fail-fast: false
    runs-on: ephemeral-${{ github.run_id }},${{ matrix.device }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure
        run: .github/workflows/configure.sh ${{matrix.maker}} ${{matrix.device}}
      - name: Build
        run: .github/workflows/build.sh ${{matrix.maker}} ${{matrix.device}}

