packages:
  all:
    target: ['x86_64']
    variants: cuda_arch=70
  mpi:
    require: openmpi
  cuda:
    buildable: false
    externals:
    - spec: cuda@11.8.0
      modules: [ cuda ]
  openmpi:
    buildable: false
    externals:
    - spec: openmpi@4.1.5
      modules: [ openmpi ]
  cmake:
    buildable: false
    externals:
    - spec: cmake@3.26.3
      modules: [ cmake ]
  intel-oneapi-mkl:
    buildable: false
    externals:
    - spec: intel-oneapi-mkl@2023.2.0
      modules: [ intel-oneapi-mkl ]
  intel-oneapi-mpi:
    buildable: false
    externals:
    - spec: intel-oneapi-mpi@2021.10.0
      modules: [ intel-oneapi-mpi ]
  gmake:
    buildable: false
    externals:
    - spec: gmake@4.4.1
      modules: [ gmake ]
  openblas:
    buildable: false
    externals:
    - spec: openblas@0.3.23
      modules: [ openblas ]
  hip:
    buildable: false
    externals:
    - spec: hip@5.7.0
      prefix: /opt/rocm-5.7.0/
  rocblas:
    buildable: false
    externals:
    - spec: rocblas@5.7.0
      prefix: /opt/rocm-5.7.0/rocblas/
  llvm-amdgpu:
    buildable: false
    externals:
    - spec: llvm-amdgpu@5.7.0
      prefix: /opt/rocm-5.7.0/llvm
  rocsolver:
    buildable: false
    externals:
    - spec: rocsolver@5.7.0
      prefix: /opt/rocm-5.7.0/rocsolver
  hsa-rocr-dev:
    buildable: false
    externals:
    - spec: hsa-rocr-dev@5.7.0
      prefix: /opt/rocm-5.7.0/hsa/

